// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package endpoint

import (
	service "github.com/andrei-cloud/pinservice/pkg/service"
	endpoint "github.com/go-kit/kit/endpoint"
)

// Endpoints collects all of the endpoints that compose a profile service. It's
// meant to be used as a helper struct, to collect all of the endpoints into a
// single parameter.
type Endpoints struct {
	VerifyEndpoint      endpoint.Endpoint
	GeneratePVVEndpoint endpoint.Endpoint
}

// New returns a Endpoints struct that wraps the provided service, and wires in all of the
// expected endpoint middlewares
func New(s service.PinService, mdw map[string][]endpoint.Middleware) Endpoints {
	eps := Endpoints{
		GeneratePVVEndpoint: MakeGeneratePVVEndpoint(s),
		VerifyEndpoint:      MakeVerifyEndpoint(s),
	}
	for _, m := range mdw["Verify"] {
		eps.VerifyEndpoint = m(eps.VerifyEndpoint)
	}
	for _, m := range mdw["GeneratePVV"] {
		eps.GeneratePVVEndpoint = m(eps.GeneratePVVEndpoint)
	}
	return eps
}
