apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: pinservice
build:
  artifacts:
    - image: pinservice
      docker:
        dockerfile: Dockerfile
  tagPolicy:
    sha256: {}
deploy:
  kubectl:
    manifests:
      - kubernetes-manifests/pinservice.yaml
