apiVersion: apps/v1
kind: Deployment
metadata:
  name: pinservice
spec:
  selector:
    matchLabels:
      app: pinservice
  template:
    metadata:
      labels:
        app: pinservice
    spec:
      hostNetwork: false
      terminationGracePeriodSeconds: 10
      preemptionPolicy: PreemptLowerPriority
      priority: 0
      containers:
      - name: pinservice
        image: pinservice
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: pinservice
spec:
  type: ClusterIP
  selector:
    app: pinservice
  ports:
  - port: 3000
    name: metrics
    targetPort: 8080
  - port: 3001
    name: service
    targetPort: 8081

